export const data = [
  {
    name: "Photo 1",
    url: "/images/spi1.jpeg",
    description: "Photo 1 description",
    date: "2020-01-01",
    type: "image/jpeg",
  },
  {
    name: "Photo 2",
    url: "/images/spi2.jpeg",
    description: "Photo 2 description",
    date: "2020-01-02",
    type: "image/jpeg",
  },
  {
    name: "Photo 3",
    url: "/images/spi3.jpeg",
    description: "Photo 3 description",
    date: "2020-01-03",
    type: "image/jpeg",
  },
  {
    name: "Photo 4",
    url: "/images/spi4.jpeg",
    description: "Photo 4 description",
    date: "2020-01-04",
    type: "image/jpeg",
  },
  {
    name: "Photo 5",
    url: "/images/spi5.jpeg",
    description: "Photo 5 description",
    date: "2020-01-05",
    type: "image/jpeg",
  },
  {
    name: "Photo 6",
    url: "/images/spi6.jpeg",
    description: "Photo 6 description",
    date: "2020-01-06",
    type: "image/jpeg",
  },
  {
    name: "Photo 7",
    url: "/images/spi7.jpeg",
    description: "Photo 7 description",
    date: "2020-01-07",
    type: "image/jpeg",
  },
  {
    name: "Photo 8",
    url: "/images/spi8.jpeg",
    description: "Photo 8 description",
    date: "2020-01-08",
    type: "image/jpeg",
  },
  {
    name: "Photo 9",
    url: "/images/spi9.jpeg",
    description: "Photo 9 description",
    date: "2020-01-09",
    type: "image/jpeg",
  },
];
